# Generated by Django 5.1.4 on 2025-01-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=255)),
                ('corp_cls', models.CharField(max_length=1)),
                ('bizr_no', models.CharField(max_length=255)),
                ('induty_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='CorpCode',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=50)),
                ('modify_date', models.DateField()),
            ],
            options={
                'db_table': 'corp_code',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('corp_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('last_called_date', models.DateField(null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
